theme: jekyll-theme-hacker
title: "Portafolio de Andres Acevedo"
description: "Pentesting | QA | Scripts | CTFs"
show_downloads: false
google_analytics:

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
